/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_keystore_KeyStoreModule */

#ifndef _Included_com_example_keystore_KeyStoreModule
#define _Included_com_example_keystore_KeyStoreModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_keystore_KeyStoreModule
 * Method:    create
 * Signature: (Ljava/lang/String;[B[BLjava/util/Map;Landroid/content/Context;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_keystore_KeyStoreModule_create
  (JNIEnv *, jclass, jstring, jbyteArray, jbyteArray, jobject, jobject);

/*
 * Class:     com_example_keystore_KeyStoreModule
 * Method:    get
 * Signature: (Ljava/lang/String;Ljava/util/Map;Landroid/content/Context;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_keystore_KeyStoreModule_get
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     com_example_keystore_KeyStoreModule
 * Method:    update
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_keystore_KeyStoreModule_update
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_keystore_KeyStoreModule
 * Method:    delete
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_keystore_KeyStoreModule_delete
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
